import pytest

from rental_pdf_generator.models import Case

CORPORATE_CASE_DATA: dict = {
    "case_id": "CASE-TEST-001",
    "applicant_type": "corporate",
    "company": {
        "company_name": "テスト商事株式会社",
        "company_kana": "テストショウジカブシキガイシャ",
        "corporate_number": "9999999999999",
        "head_office_address": "東京都千代田区テスト町1-1-1",
        "representative_name": "テスト 太郎",
        "representative_kana": "テスト タロウ",
        "representative_birth_date": "1980年01月01日",
        "representative_age": "46",
        "representative_address": "東京都千代田区テスト町2-2-2",
        "phone": "03-9999-0001",
        "email": "test@example.test",
        "established_date": "2020年01月01日",
        "capital": "5,000,000円",
        "business_description": "テスト用事業の運営",
        "employee_count": "5名",
        "fiscal_year_end": "12月31日",
    },
    "property": {
        "property_name": "テストマンション",
        "room_number": "101",
        "property_address": "東京都新宿区テスト1-1-1",
        "rent": "100,000円",
        "management_fee": "5,000円",
        "desired_move_in_date": "2026年07月01日",
        "usage_purpose": "社宅",
    },
    "financials": {
        "fiscal_year": "2025年度",
        "sales": "50,000,000円",
        "operating_income": "5,000,000円",
        "ordinary_income": "4,800,000円",
        "net_income": "3,000,000円",
        "total_assets": "20,000,000円",
        "total_liabilities": "8,000,000円",
        "net_assets": "12,000,000円",
    },
    "business_plan": {
        "plan_period": "2026年度",
        "business_overview": "テスト事業の拡大を計画しています。",
        "revenue_plan": "新規顧客の獲得により売上を20%増加予定。",
        "hiring_plan": "エンジニア2名採用予定。",
        "risk_factors": "市場競争の激化。",
        "trade_name": "テスト屋号",
        "opening_date": "2026年04月01日",
        "business_category": "テスト業種",
        "target_customers": "テスト顧客",
        "initial_capital": "5,000,000円",
        "funding_plan": "自己資金のみ",
        "monthly_revenue_target": "500,000円",
        "monthly_cost_estimate": "200,000円",
        "founder_background": "テスト経歴",
        "competitive_advantage": "テスト優位性",
        "marketing_strategy": "テスト戦略",
    },
    "documents": [
        {"document_type": "rental_application_corporate", "variant": "standard"},
        {"document_type": "registry_certificate", "variant": "registry_table"},
        {"document_type": "financial_statement", "variant": "financial_summary"},
        {"document_type": "business_plan", "variant": "narrative"},
    ],
}

INDIVIDUAL_CASE_DATA: dict = {
    "case_id": "CASE-TEST-002",
    "applicant_type": "individual",
    "applicant": {
        "name": "テスト 花子",
        "kana": "テスト ハナコ",
        "birth_date": "1995年06月15日",
        "age": "30",
        "gender": "女性",
        "current_address": "東京都杉並区テスト1-1-1",
        "phone": "090-9999-0002",
        "email": "hanako@example.test",
        "id_document_type": "運転免許証",
    },
    "employment": {
        "employer_name": "テスト株式会社",
        "department": "総務部",
        "job_title": "主任",
        "years_employed": "5年",
        "annual_income": "4,000,000円",
        "employer_phone": "03-9999-0003",
        "employer_address": "東京都渋谷区テスト2-2-2",
    },
    "property": {
        "property_name": "テストアパート",
        "room_number": "203",
        "property_address": "東京都世田谷区テスト3-3-3",
        "rent": "80,000円",
        "management_fee": "5,000円",
        "desired_move_in_date": "2026年08月01日",
        "usage_purpose": "居住用",
    },
    "emergency_contact": {
        "name": "テスト 一郎",
        "relation": "父",
        "phone": "090-9999-0004",
        "address": "埼玉県さいたま市テスト4-4-4",
    },
    "income": {
        "income_year": "2025年",
        "annual_income": "4,000,000円",
        "monthly_income": "333,000円",
        "income_type": "給与所得",
        "issuer_name": "テスト株式会社",
        "issue_date": "2026年05月01日",
        "base_salary": "270,000円",
        "overtime_allowance": "30,000円",
        "commuting_allowance": "10,000円",
        "bonus": "600,000円",
        "certificate_expiry": "2026年08月01日",
    },
    "guarantor": {
        "name": "テスト 一郎",
        "kana": "テスト イチロウ",
        "birth_date": "1965年01月01日",
        "relationship": "父",
        "current_address": "埼玉県さいたま市テスト4-4-4",
        "phone": "090-9999-0004",
        "employer_name": "テスト製造株式会社",
        "annual_income": "6,000,000円",
    },
    "identity_document": {
        "license_number": "999999999999",
        "expiry": "2028年06月15日",
        "issue_date": "2018年06月15日",
        "issue_place": "東京都",
    },
    "documents": [
        {"document_type": "rental_application_individual", "variant": "standard"},
        {"document_type": "income_certificate", "variant": "salary_certificate"},
        {"document_type": "identity_document", "variant": "drivers_license"},
    ],
}


@pytest.fixture
def corporate_case_data() -> dict:
    return CORPORATE_CASE_DATA.copy()


@pytest.fixture
def corporate_case() -> Case:
    return Case.model_validate(CORPORATE_CASE_DATA)


@pytest.fixture
def individual_case_data() -> dict:
    return INDIVIDUAL_CASE_DATA.copy()


@pytest.fixture
def individual_case() -> Case:
    return Case.model_validate(INDIVIDUAL_CASE_DATA)


CORPORATE_EXTENDED_CASE_DATA: dict = {
    **CORPORATE_CASE_DATA,
    "case_id": "CASE-TEST-EXT-CORP",
    "guarantor": {
        "name": "テスト 連帯",
        "kana": "テスト レンタイ",
        "birth_date": "1982年02月02日",
        "relationship": "代表取締役の配偶者",
        "current_address": "東京都千代田区テスト町2-2-2",
        "phone": "090-9999-0009",
        "employer_name": "テスト電機株式会社",
        "annual_income": "9,000,000円",
    },
    "parent_company": {
        "company_name": "テストホールディングス株式会社",
        "corporate_number": "1111111111111",
        "head_office_address": "東京都港区テスト10-10-10",
        "representative_name": "親会社 代表",
        "capital": "100,000,000円",
        "established_date": "2010年04月01日",
        "business_description": "グループ企業の経営管理",
        "fiscal_year_end": "3月31日",
        "relationship": "100%親会社",
    },
    "parent_company_financials": {
        "fiscal_year": "2025年度",
        "sales": "500,000,000円",
        "operating_income": "60,000,000円",
        "ordinary_income": "58,000,000円",
        "net_income": "40,000,000円",
        "total_assets": "300,000,000円",
        "total_liabilities": "120,000,000円",
        "net_assets": "180,000,000円",
    },
    "business_license": {
        "license_name": "飲食店営業許可",
        "license_number": "TEST-XYZ-12345",
        "licensee_name": "テスト商事株式会社",
        "business_type": "飲食店営業",
        "license_address": "東京都新宿区テスト1-1-1",
        "issue_date": "2024年01月10日",
        "expiry": "2032年01月09日",
        "issuing_authority": "テスト保健所",
    },
    "corporate_guarantee": {
        "guarantor_name": "テスト 太郎",
        "guarantor_kana": "テスト タロウ",
        "guarantor_address": "東京都千代田区テスト2-2-2",
        "guarantor_birth_date": "1980年01月01日",
        "relationship_to_company": "代表取締役",
        "guarantee_amount": "3,600,000円（賃料36ヶ月分）",
        "guarantee_period": "賃貸借契約期間に同じ",
        "contract_date": "2026年06月20日",
    },
    "business_license_application": {
        "applicant_name": "テスト商事株式会社",
        "business_type": "飲食店営業（テスト用）",
        "license_address": "東京都新宿区テスト1-1-1",
        "application_date": "2026年10月20日",
        "receipt_number": "TEST-AP-99999",
        "issuing_authority": "テスト保健所",
        "expected_issue_date": "2026年12月10日",
        "status_note": "申請中につき許可書未交付",
    },
    "funding_evidence": {
        "as_of_date": "2026年07月31日",
        "own_capital": "20,000,000円",
        "bank_loan": "30,000,000円",
        "bank_loan_lender": "テスト公庫",
        "investment": "120,000,000円",
        "investor_name": "テストVC",
        "subsidy": "5,000,000円",
        "subsidy_source": "テスト助成事業",
        "total_funding": "175,000,000円",
        "fund_usage": "テスト資金使途",
        "monthly_rent_coverage": "月額賃料の36ヶ月分以上",
        "evidence_documents": "① 資本金払込証明書 ② 融資契約書 ③ 投資契約書",
    },
    "business_use_pledge": {
        "pledger_name": "テスト商事株式会社",
        "representative_name": "テスト 太郎",
        "pledge_date": "2026年11月01日",
        "original_business_type": "飲食店営業（イートイン併設）",
        "changed_business_type": "テイクアウト専門",
        "change_reason": "テスト用変更理由",
        "license_required": "不要",
    },
    "previous_financials": {
        "fiscal_year": "2024年度",
        "sales": "40,000,000円",
        "operating_income": "4,000,000円",
        "ordinary_income": "3,800,000円",
        "net_income": "2,400,000円",
        "total_assets": "18,000,000円",
        "total_liabilities": "7,000,000円",
        "net_assets": "11,000,000円",
    },
    "trial_balance": {
        "fiscal_period": "2026年10月度（月次）",
        "cash": "12,000,000円",
        "accounts_receivable": "4,500,000円",
        "inventory": "600,000円",
        "total_current_assets": "17,100,000円",
        "fixed_assets": "5,400,000円",
        "total_assets": "22,500,000円",
        "accounts_payable": "1,800,000円",
        "short_term_borrowings": "2,000,000円",
        "total_current_liabilities": "3,800,000円",
        "long_term_borrowings": "5,200,000円",
        "total_liabilities": "9,000,000円",
        "total_net_assets": "13,500,000円",
        "revenue": "28,000,000円",
        "cost_of_sales": "8,400,000円",
        "gross_profit": "19,600,000円",
        "sga_expenses": "17,000,000円",
        "operating_profit": "2,600,000円",
    },
    "corporate_housing_usage": {
        "occupant_name": "テスト 役員",
        "occupant_relation": "役員（取締役）",
        "occupant_department": "経営企画部",
        "occupant_job_title": "取締役",
        "occupant_family": "妻・子1人",
        "rent_subsidy_amount": "80,000円",
        "rent_subsidy_ratio": "80%",
        "contract_name": "法人契約",
        "parking_required": "希望",
    },
    "corporate_store_usage": {
        "business_format": "飲食店（カフェ業態）",
        "operating_hours": "8:00〜22:00",
        "operating_days": "年中無休",
        "closed_days": "なし",
        "expected_visitors_per_day": "120名",
        "noise_level": "通常会話レベル",
        "odor_level": "コーヒー香程度",
        "construction_required": "厨房設置・看板取付あり",
        "waste_type": "生ごみ・紙ごみ・容器包装",
    },
}


INDIVIDUAL_EXTENDED_CASE_DATA: dict = {
    **INDIVIDUAL_CASE_DATA,
    "case_id": "CASE-TEST-EXT-IND",
    "guarantor_2": {
        "name": "テスト 二郎",
        "kana": "テスト ジロウ",
        "birth_date": "1968年03月03日",
        "relationship": "叔父",
        "current_address": "東京都品川区テスト5-5-5",
        "phone": "090-9999-0005",
        "employer_name": "テスト保証株式会社",
        "annual_income": "7,000,000円",
    },
    "guarantor_2_income": {
        "income_year": "2025年",
        "annual_income": "7,000,000円",
        "monthly_income": "583,000円",
        "income_type": "給与所得",
        "employer_name": "テスト保証株式会社",
        "employer_phone": "03-9999-0006",
        "employer_address": "東京都品川区テスト6-6-6",
        "issue_date": "2026年05月01日",
        "base_salary": "450,000円",
        "bonus": "1,400,000円",
    },
    "guarantor_2_identity_document": {
        "license_number": "888888888888",
        "expiry": "2027年03月03日",
        "issue_date": "2022年03月03日",
        "issue_place": "東京都",
    },
    "guarantee_company": {
        "company_name": "テスト家賃保証株式会社",
        "company_address": "東京都中央区テスト7-7-7",
        "company_phone": "03-9999-0007",
        "application_date": "2026年07月15日",
        "plan_name": "テストプラン",
        "initial_fee": "賃料60%",
        "monthly_fee": "賃料1%",
        "coverage_amount": "1,920,000円",
        "contract_period": "1年自動更新",
    },
    "offer_letter": {
        "employer_name": "テスト新会社株式会社",
        "employer_address": "東京都品川区テスト8-8-8",
        "employer_phone": "03-9999-0008",
        "department": "営業部",
        "job_title": "マネージャー",
        "start_date": "2026年09月01日",
        "expected_annual_income": "6,500,000円",
        "expected_monthly_income": "470,000円",
        "issue_date": "2026年07月10日",
        "hr_contact_name": "テスト 人事",
    },
    "previous_employment": {
        "employer_name": "テスト前職株式会社",
        "employer_address": "東京都新宿区テスト9-9-9",
        "employment_period": "2020年04月01日 〜 2026年08月31日",
        "income_year": "2025年",
        "gross_income": "4,000,000円",
        "withholding_tax": "150,000円",
        "social_insurance": "560,000円",
        "end_date": "2026年08月31日",
    },
    "student": {
        "name": "テスト 学生",
        "kana": "テスト ガクセイ",
        "birth_date": "2006年04月01日",
        "school_name": "テスト大学",
        "department": "経済学部",
        "grade": "学部1年",
        "student_number": "T260123-456",
        "enrollment_date": "2026年04月01日",
        "expected_graduation_date": "2030年03月31日",
        "relationship_to_applicant": "長男",
    },
    "previous_income": {
        "income_year": "2024年",
        "annual_income": "3,800,000円",
        "monthly_income": "316,000円",
        "income_type": "給与所得",
        "issuer_name": "テスト株式会社",
        "issue_date": "2025年05月01日",
        "base_salary": "260,000円",
        "overtime_allowance": "25,000円",
        "commuting_allowance": "10,000円",
        "bonus": "560,000円",
        "certificate_expiry": "2025年08月01日",
    },
    "soho_usage": {
        "residential_ratio": "60%",
        "business_ratio": "40%",
        "business_type": "Webデザイン",
        "business_overview": "テスト用 Web デザイン業務",
        "visitor_frequency": "月1回",
        "trade_name": "テストデザインスタジオ",
        "has_signboard": "なし",
    },
    "business_opening_notice": {
        "issuing_tax_office": "テスト税務署",
        "submission_date": "2026年06月01日",
        "tax_address": "東京都杉並区テスト1-1-1",
        "owner_name": "テスト 花子",
        "owner_birth_date": "1995年06月15日",
        "occupation": "テスト職業",
        "trade_name": "テスト屋号",
        "opening_date": "2026年06月01日",
        "business_overview": "テスト事業概要",
        "employs_others": "なし",
    },
    "bank_balance_certificate": {
        "account_holder": "テスト 花子",
        "bank_name": "テストメガバンク",
        "branch_name": "テスト支店",
        "account_type": "普通預金",
        "account_number": "1111111",
        "balance_as_of_date": "2026年09月01日",
        "balance_amount": "3,500,000円",
        "issue_date": "2026年09月02日",
        "issuer_staff": "テスト 担当",
    },
    "guarantor_seal_certificate": {
        "registration_number": "テスト-第99999号",
        "registration_date": "2020年05月15日",
        "issuing_municipality": "東京都テスト区",
        "issue_date": "2026年07月25日",
    },
    "guarantor_residence_certificate": {
        "gender": "男性",
        "honseki": "東京都テスト区テスト1-1-1",
        "head_of_household": "テスト 一郎",
        "relation_to_head": "世帯主",
        "resident_since": "2018年04月01日",
        "issuing_municipality": "東京都テスト区",
        "issue_date": "2026年07月25日",
    },
}


@pytest.fixture
def corporate_extended_case() -> Case:
    return Case.model_validate(CORPORATE_EXTENDED_CASE_DATA)


@pytest.fixture
def individual_extended_case() -> Case:
    return Case.model_validate(INDIVIDUAL_EXTENDED_CASE_DATA)
